services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - qna_network
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/qna_db
    depends_on:
      - mongo
    working_dir: /server

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    networks:
      - qna_network
    volumes:
      - ./client:/app
      - /app/build
      - /app/.dart_tool
    working_dir: /app
    command: ["flutter", "run", "-d", "web-server", "--web-port", "8080", "--web-hostname", "0.0.0.0"]
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - qna_network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  qna_network:
    driver: bridge

